### ISSUE TITLE
Confusion entre instances GitLab et GitHub ?

### ISSUE THREAD

**Issue by bzg** [codegouvfr/ecosystems-repos#1]
Cf. [ce tweet](https://twitter.com/alwyn974/status/1738427658734862649) que je cite:

> Si on va sur http://data.code.gouv.fr, c'est écrit 5 instances gitlab, mais la première instance par exemple ne contient que des liens vers des repos GitHub

**Comment by simkim** [comment]
C'est spécifique à cette org qui mirror sur gitlab des dépots github.

**Comment by bzg** [comment]
Compris, merci !
