### ISSUE TITLE
Mettre en place un dump/backup des bases de données

### ISSUE THREAD

**Issue by bzg** [codegouvfr/ecosystems-repos#10]
- [x] Faire dumps des bases (@simkim)
- [x] Sauvegarder ces dumps sur un autre serveur (@bzg)

**Comment by simkim** [comment]
3 derniers jours
12 derniers mois
15 backup max de 3Go = 45Go soit 5% de l'espace disque -> ok

**Comment by bzg** [comment]
Top - j'ai backupé le `.sql` + `/opt/vault/repos` sur un autre serveur.
