### ISSUE TITLE
Décompte du nombre de dépôts désynchronisé

### ISSUE THREAD

**Issue by bzg** [codegouvfr/ecosystems-repos#3]
https://data.code.gouv.fr/hosts/gitlab.univ-nantes.fr/owners indique toujours "1 dépôt" alors qu'en cliquant sur les organisations on en trouve souvent plus.

**Comment by bzg** [comment]
Comme discuté ce matin, voir avec ecosyste.ms quelle solution renvoie des chiffres cohérents et correspondant à la réalité.

**Comment by simkim** [comment]
Normalement corrigé dans le calcul et fixé en prod. Tu peux ferme si c'est bon pour toi
