### ISSUE TITLE
On trouve des comptes d'utilisateurs ("kind: user") dans les owners

### ISSUE THREAD

**Issue by bzg** [codegouvfr/ecosystems-repos#6]
Hormis pour les plateformes qui n'ont pas de notion de « compte d'organisation » (comme SourceHut), nous n'avons jamais besoin de collecter les infos pour les comptes qui sont "kind: user".

Peut-on paramétrer `repos` pour qu'il ne collecte (et expose via l'API) que les comptes d'organisation (pour certaines plateformes comme GitLab et GitHub) et tous les comptes (pour d'autres plateformes comme SourceHut)?

**Comment by simkim** [comment]
On peut ajouter une config pour ça

**Comment by bzg** [comment]
Oui - voir aussi https://github.com/codegouvfr/ecosystems-repos/issues/8

**Comment by bzg** [comment]
Est-ce OK de fermer l'issue ? C'est OK en production ?
