### ISSUE TITLE
Ne collecter les infos que des "groupes" GitLab

### ISSUE THREAD

**Issue by bzg** [codegouvfr/ecosystems-repos#8]
https://code.gouv.fr/sources ne doit pas collecter d'information sur les dépôts qui ne sont pas associés à des comptes d'organisation (pour GitHub), à des groupes ou sous-groupes (pour GitLab).

De façon général, nous ignorons les dépôts qui ne sont *que* publiés par des utilisateurs.

Nous faisons une exception pour SourceHut, où la notion de comptes d'organisation ou de groupe n'existe pas encore.

Je note ici l'issue pour trouver une solution pour ne *plus* collecter les dépôts publiés par des utilisateurs via des instances GitLab.

**Comment by simkim** [comment]
J'ai déployé le filtre qui ne synchronise plus les users de gitlab

Cependant on a des owner de type "user" actuellement dans la base:

{nil=>116, "gitlab"=>372, "github"=>7}

On supprime les 372 de gitlab avec leurs repos ?

Les 7 users de github : ["DGTresor",
 "HolAutisme",
 "InriaMecsci",
 "AFB-dataviz",
 "dsi-github",
 "orleans-metropole",
 "administration-solrep"]

On les garde ?

Si oui je dois renommer SKIP_USER_REPOS en GITLAB_SKIP_USER_REPOS

**Comment by bzg** [comment]
Quand ce sont des owners de forges non 100% dédiées au service public (e.g. github.com, gitlab.com, framagit.org, etc.), on doit les supprimer dans [comptes-organismes-publics.yml](https://git.sr.ht/~codegouvfr/codegouvfr-data/tree/main/item/comptes-organismes-publics.yml), pas depuis un filtrage ecosyste.ms.

Pour les owners de toutes les autres forges, le filtrage doit se faire depuis ecosyste.ms.

J'ai fait la correction pour les mauvais comptes GitHub.

Dois-je supprimer des comptes de gitlab.com ou d'autres forges "grand public" ?

**Comment by simkim** [comment]
- Non pas de filtrage à faire sur des forges grands publics
- Je nettoie le reste

**Comment by bzg** [comment]
Est-ce qu'on peut fermer l'issue ?
